-- configs/hardtime.lua

require("hardtime").setup {
  max_time = 1000,
  max_count = 3,
  disable_mouse = false,
  hint = true,
  notification = true,
  allow_different_key = true,
  enabled = true,
  resetting_keys = {
    ["1"] = { "n", "x" },
    ["2"] = { "n", "x" },
    ["3"] = { "n", "x" },
    ["4"] = { "n", "x" },
    ["5"] = { "n", "x" },
    ["6"] = { "n", "x" },
    ["7"] = { "n", "x" },
    ["8"] = { "n", "x" },
    ["9"] = { "n", "x" },
    ["c"] = { "n" },
    ["C"] = { "n" },
    ["d"] = { "n" },
    ["x"] = { "n" },
    ["X"] = { "n" },
    ["y"] = { "n" },
    ["Y"] = { "n" },
    ["p"] = { "n" },
    ["P"] = { "n" },
    ["gp"] = { "n" },
    ["gP"] = { "n" },
    ["."] = { "n" },
    ["="] = { "n" },
    ["<"] = { "n" },
    [">"] = { "n" },
    ["J"] = { "n" },
    ["gJ"] = { "n" },
    ["~"] = { "n" },
    ["g~"] = { "n" },
    ["gu"] = { "n" },
    ["gU"] = { "n" },
    ["gq"] = { "n" },
    ["gw"] = { "n" },
    ["g?"] = { "n" },
  },
  restriction_mode = "block", -- block or hint
  restricted_keys = {
    ["h"] = { "n", "x" },
    ["j"] = { "n", "x" },
    ["k"] = { "n", "x" },
    ["l"] = { "n", "x" },
    ["-"] = { "n", "x" },
    ["+"] = { "n", "x" },
    ["gj"] = { "n", "x" },
    ["gk"] = { "n", "x" },
    ["<CR>"] = { "n", "x" },
    ["<C-M>"] = { "n", "x" },
    ["<C-N>"] = { "n", "x" },
    ["<C-P>"] = { "n", "x" },
  },
  disabled_keys = {
    ["<Up>"] = { "", "i" },
    ["<Down>"] = { "", "i" },
    ["<Left>"] = { "", "i" },
    ["<Right>"] = { "", "i" },
  },
  disabled_filetypes = {
    "NvimTree",
    "TelescopePrompt",
    "aerial",
    "alpha",
    "checkhealth",
    "dapui*",
    "Diffview*",
    "Dressing*",
    "help",
    "httpResult",
    "lazy",
    "lspinfo",
    "Neogit*",
    "mason",
    "neo%-tree*",
    "netrw",
    "notify",
    "qf",
    "trouble",
    "fugitive",
  },
}
